### PR TITLE
set method access level in Database/Schema/Grammars/MySqlGrammar.php …

### PR DESCRIPTION
**Pull request by ahuggins**
…to public

### CODE REVIEW

**Comment by ahuggins** [comment]
Best I can tell, some of these methods in the Grammars\MySqlGrammar.php were set to protected. And it looks like prior to Laravel 5.5, some of these were never defined. But since they have been defined in the base Laravel 5.5 MySqlGrammar class, with an access level of `public` it is necessary to update these methods to be `public` instead of `protected`.

Let me know if there is any question about this theory. Thanks!

**Comment by ahuggins** [comment]
Also, the reason I had to look into this, tried to run `php artisan migrate` after installing this package, and was getting errors saying this: `Access level to ElevenLab\GeoLaravel\Database\Schema\Grammars\MySqlGrammar::typePoint() must be public (as in class Illuminate\Database\Schema\Grammars\MySqlGrammar)`

I went through and checked each method...which ended up being all of them.

**Comment by ahuggins** [comment]
For additional reference, here is the MySqlGrammar class in L5.5: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php

**Comment by desh901** [comment]
Thanks for the PR and the reference, we will test out your modifications also with previous versions of Laravel to see if there is any conflict with your solution, if not we will merge your PR!

**Comment by ahuggins** [comment]
So, looking into it again, it looks like you do not even need this package since in L5.5, these Geo spatial functions are supported on the main Framework: 

https://github.com/laravel/framework/commits/5.5/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php

Was only added Nov 2, 2017...which is probably why I ran into this issue.

There could be a reason still that this package provides additional functionality or convenience, but in terms of support, L5.5 gets it. Or it might mean that some of the package code could be removed.

Thanks for the help!

**Comment by ahuggins** [comment]
Actually, looks like Sept 6, 2017 was when these Geo Spatial functions were added...Nov 2, was some minor tweaking.

**Comment by desh901** [comment]
Ok so it seems like Laravel 5.5 now supports geospatial types. I will add this info in the README when possible so the standard Schema can be use instead of this library. Thanks for the info!

**Comment by jwatkins0101** [comment]
Will you pull this in?

**Pull request closed without merging**
